### ISSUE TITLE
option for changing alarm sound

### ISSUE THREAD

**Issue by paulle** [alaskalinuxuser/app_hourglass#1]
For first thank you for the nice app. But it would be nice to have an option for changing the alarm sound, because sometimes it's useful to have louder or stronger sound.

**Comment by alaskalinuxuser** [comment]
Thanks for the great feedback! That is a wonderful idea. I have just done so:
commit d9a2e0c7389fcb672823989cce4326ba23252e4a
I added a button that allows you to change between several sounds (the bell, a loud foghorn, and some soft bird chirps) as well as an on/off button for the vibration.

Again, thanks for taking the time to look at the app, and for making a suggestion! If you are using the app from F-Droid, it may take a week or so for the new version to get built there. The Play Store version is up to date now.

**Comment by paulle** [comment]
Thank you, the foghorn is what I need and the on/off option for vibration is fine. Will wait till it is in the f-droid repo. Thanks for the quick update.

Am 9. März 2017 22:27:26 MEZ schrieb AlaskaLinuxUser <notifications@github.com>:
>Thanks for the great feedback! That is a wonderful idea. I have just
>done so:
>commit d9a2e0c7389fcb672823989cce4326ba23252e4a
>I added a button that allows you to change between several sounds (the
>bell, a loud foghorn, and some soft bird chirps) as well as an on/off
>button for the vibration.
>
>Again, thanks for taking the time to look at the app, and for making a
>suggestion! If you are using the app from F-Droid, it may take a week
>or so for the new version to get built there. The Play Store version is
>up to date now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_hourglass/issues/1#issuecomment-285488728

-- 
K-9 Mail
