### ISSUE TITLE
Add continuous notification

### ISSUE THREAD

**Issue by brunetton** [alaskalinuxuser/app_hourglass#10]
Hi
I love this open source app and using it quite often. But sometimes my phone is in my pocket and I'm listening to music and I miss the time ended notification ! The vibration is short, easy to miss, same thing for the notifications sounds. I'd find "logical" to have a continuous notification that vibrates and rings until I manually stop it (from notification bar or inside app).
Is this feature planned for a future release ? 
Thanks

**Comment by alaskalinuxuser** [comment]
Good idea. I don't have an Android phone anymore (switched to Ubuntu) but I'll take a look at it.

**Comment by alaskalinuxuser** [comment]
Added this option with commit https://github.com/alaskalinuxuser/app_hourglass/commit/f24032fb4950492d98466fd04681fb73637ab534

Be sure to give some feedback. This works in that once you click "continuous alarm button" when the timer goes off, it resets the timer to 2 seconds and repeats until you click the "continuous alarm button" to be off.

Hopefully that helps! Thanks for the great ideas. Again, you can download here on GitHub: https://github.com/alaskalinuxuser/app_hourglass/blob/master/app/hourglass_1.8.apk

Or wait for the updates to hit the Playstore or FDroid.

**Comment by alaskalinuxuser** [comment]
![time_up](https://user-images.githubusercontent.com/19839527/39495708-e71c9722-4d47-11e8-8e50-4a7a66740d3f.png)

**Comment by alaskalinuxuser** [comment]
Also added notification cancel button! Be sure to check it out in version 1.9!
![screenshot from 2018-05-02 13-12-03](https://user-images.githubusercontent.com/19839527/39549704-496eecc2-4e0b-11e8-9b05-5900667384c2.png)

**Comment by brunetton** [comment]
This seems great ! I can't wait to test the new version. For some reasons I can't install it via APK file :( I'll have to wait to the F-Droid release.
Thanks
