### ISSUE TITLE
time sllder vertical

### ISSUE THREAD

**Issue by paulle** [alaskalinuxuser/app_hourglass#2]
If the time sllder would be vertical instead of horizontal, it would be easier to put the time more "fine grained" because the slider would be longer.

**Comment by alaskalinuxuser** [comment]
Great comment. I love your enthusiasm!

As for the timer slider, the user can make it longer by turning their phone on it's side, switching to landscape mode. So, I plan to leave that part as is.

Thanks for the great suggestion, and feel free to make more comments!
