### ISSUE TITLE
changing from vertical to horizontal position stops hourglass 

### ISSUE THREAD

**Issue by paulle** [alaskalinuxuser/app_hourglass#3]
If I put put hourglass to 5 minutes, start the countdown and when move the from vertical to horizontal hourglass stops the countdown and jumps back otherwise to 5 minutes.

**Comment by alaskalinuxuser** [comment]
Great catch. This does not happen on my Nougat phone, but it does happen on my Lollipop phone. Odd. An interesting side note, when this happens, the timer is still active, and will still go off on time, but you cannot watch the countdown, even if you leave the app and come back. Interesting. I will look into fixing this.

**Comment by alaskalinuxuser** [comment]
https://github.com/alaskalinuxuser/app_hourglass/commit/62e9cff431237e6d7ec5b1cd68006be13529df72
Issue is fixed by forcing portrait mode for now. Also added manual time entry.

**Comment by paulle** [comment]
Interesting I'm using nougat(7.0) and it happens to me.

**Comment by alaskalinuxuser** [comment]
So, what do you think? Did that help?

Also, if I may be so bold, have you tried my Ship, Captain, and Crew game (also on fdroid and the play store)?

**Comment by paulle** [comment]
No, because I don't use games. Till today I've a game on my PC that I didn't finish since two years.

Am 18. März 2017 17:04:32 MEZ schrieb AlaskaLinuxUser <notifications@github.com>:
>So, what do you think? Did that help?
>
>Also, if I may be so bold, have you tried my Ship, Captain, and Crew
>game (also on fdroid and the play store)?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_hourglass/issues/3#issuecomment-287555557

-- 
K-9 Mail
