### ISSUE TITLE
Manual time entry

### ISSUE THREAD

**Issue by jasonmacduffie** [alaskalinuxuser/app_hourglass#4]
Hello, I find it difficult to set the timer for a specific time like 1 minute. I think it would be nice to be able to enter a time manually with the keyboard.

**Comment by alaskalinuxuser** [comment]
I was originally striving for a simplistic timer that was easy to set, but your right, it does make it difficult if you need to set a specific exact time. I am going to look into a way to implement this, hopefully without clutter. Thanks for the feedback!

**Comment by alaskalinuxuser** [comment]
https://github.com/alaskalinuxuser/app_hourglass/commit/62e9cff431237e6d7ec5b1cd68006be13529df72
Issue is fixed by added manual time entry.

**Comment by alaskalinuxuser** [comment]
So, what do you think? Did that help?

Also, if I may be so bold, have you tried my Ship, Captain, and Crew game (also on fdroid and the play store)?

**Comment by jasonmacduffie** [comment]
Great, it's perfect now. Thanks a lot.

I have not tried it yet, but I will check it out.
