### ISSUE TITLE
improve manual time entry

### ISSUE THREAD

**Issue by spaetz** [alaskalinuxuser/app_hourglass#7]
Thanks for hourglass. I use the manual time entry a lot (I use it to time student group discussions). I believe it could be made much easier to use:
1) when I enter the textfield, the cursor is positioned somewhere. It would be nice to either preselect all minutes or all seconds, depending on where I put the focus.
2) By default, all minutes should be selected, so that I can just start typing the number of minutes I need (and ideally pop up the keyboard automatically as well.
3) When I delete everything and just enter 10, hourglass returns to the main screen, ignoring my entry. It should recognize 10 as 10:00.

**Comment by alaskalinuxuser** [comment]
Thanks for the kind words and the suggestions. I'll look into this next week.

**Comment by alaskalinuxuser** [comment]
Added with commit: https://github.com/alaskalinuxuser/app_hourglass/commit/fb28250c74e59582e887ede69cf75c1f061caf3c

**Comment by alaskalinuxuser** [comment]
Thanks for the great feedback @spaetz!

**Comment by alaskalinuxuser** [comment]
You can download the 1.6 apk from the github, or wait for the update to hit f-droid and the play store.

**Comment by spaetz** [comment]
Whoa, that was quick! I will wait for the next fdroid version, thanks. Can I donate a few € somehow as token of appreciation or should I give them to some charity?

**Comment by alaskalinuxuser** [comment]
Thank you so much! You might want to see the end product first! ;)

I do have a donate button on XDA, or on my website, thealaskalinuxuser.com and donations are always appreciated. I also like supporting local charities that feed, cloth, or house the homeless. Here in Fairbanks, Alaska, I support the stone soup cafe and the rescue mission. If you feel so led, you could donate to any local charity in your area as well.
