### ISSUE TITLE
Show remaining time in notification

### ISSUE THREAD

**Issue by brunetton** [alaskalinuxuser/app_hourglass#9]
I love this open source app but I only miss a little thing: I'd like to be able to know remaining time without changing my current app when HourGlass is running in background. For this I'd like the notification to showo me remaning time.

Thanks

**Comment by alaskalinuxuser** [comment]
Good idea. I don't have an Android phone anymore (switched to Ubuntu) but I'll take a look at it.

**Comment by alaskalinuxuser** [comment]
Added this feature in commit https://github.com/alaskalinuxuser/app_hourglass/commit/bb1ebbf07c34d3cea4a35dda531ca50cf337d24c

Thanks for the great idea!

You can download the version 1.7 apk at GitHub: 

https://github.com/alaskalinuxuser/app_hourglass/blob/master/app/hourglass_1.7.apk

Or wait for Fdroid or the Playstore to update.

**Comment by alaskalinuxuser** [comment]
![timer_notification](https://user-images.githubusercontent.com/19839527/39493590-e4bad640-4d3f-11e8-9e52-0d61d776f982.png)
